### ISSUE TITLE
Mac: Test Run Successful 🎉

### ISSUE THREAD

**Issue by asharirfan** [ahmadawais/create-guten-block#10]
### Is this a bug report?
No

### Environment:
  OS: macOS Sierra 10.12.6
  CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Node: 9.3.0
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found

### Browsers:
  Chrome: 63.0.3239.132
  Chrome Canary: Not Found
  Firefox: 57.0.4
  Firefox Developer Edition: Not Found
  Firefox Nightly: Not Found
  Safari: 11.0.2
  Safari Technology Preview: Not Found

### Packages: (wanted => installed)
  cgb-scripts: 1.9.1 => 1.9.1

### Steps to Reproduce

I have tested the latest version on macOS Sierra 10.12.6 and here are my tests and their conclusions:

1. Installed Create Guten Block using `npm install create-guten-block --global`
2. Created a new Guten block called `test-block` using command `create-guten-block test-block` and everything went fine. Terminal Screenshot:
![alt text](https://cl.ly/owj5/🔥 "Screenshot")
3. Then I changed PWD to `test-block` and run `npm start` in the terminal — this command watch for changes in the source code present in the `test-block` directory.
4. Introduced some changes in the source content file `test-block/block/block.js`, in stylesheets `editor.scss` — Editor styles — and `style.scss` — Front-end styles.

Content changes:
![alt text](https://cl.ly/oxo7/🔥 "Content Changes")

Style changes:
![alt text](https://cl.ly/oxHu/🔥 "Style changes")

5. Introduced a wrong tag to check errors:
![alt text](https://cl.ly/oxxm/🔥 "Wrong Tag")

Resulted in errors in terminal:
![alt text](https://cl.ly/oxFB/🔥 "Terminal Errors")

Made a complementary GIF for my test block:
![alt text](https://cl.ly/oxvy/🔥 "GIF")

6. `npm run build` runs successfully.
![alt text](https://cl.ly/ownW/🔥 "npm run build")

7. Ejected successfully using `npm run eject`.
![alt text](https://cl.ly/owQe/🔥 "npm run build")

That's all 🙌

**Comment by ahmadawais** [comment]
Thanks for reporting that. Love that you're testing it.

**Comment by asharirfan** [comment]
I am glad to be onboard 🙂
Loved the testing ⚡️
