### ISSUE TITLE
Gutenberg 4.0 totally broken with create-guten-block

### ISSUE THREAD

**Issue by weavertheme** [ahmadawais/create-guten-block#100]
## Bug Report

I think this could be a very general bug affecting almost any WP plugin built for GB using create-guten-block.

I don't know who broke what for sure, but as of GB 4.0.0, my plugin built with create-guten-block has totally failed - any re-edit of a block will result will result in a "This block contains unexpected or invalid content."

My plugin has worked perfectly since last march or so, and started to fail with 4.0.
The cause seems to be a failure of initializing at least some of the 'attributes' array when Gutenberg tries to validate the block. It "expects" the original values for many of the attributes in the wrapping block <div>, but "sees" the actual values as set by the inspector.js code.

It is as if the base class is not being properly constructed when invoked by the block validator.

It don't know what changed in 4.0, but I have also seen some similar issues with 3.9.

I don't know if the problem is in the code generated by create-guten-block, or if there is some change in how gb is setting up the class for a block before invoking block validation.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

### Steps to Reproduce

(Write your steps here:)
It is not easy to explain exactly what is going, but it is very easy to duplicate the issue simply by testing out my plugin and using Firefox's developer tool to see the error message from the block validator.

1. Update to GB 4.0.0
2. Install my plugin, available as "Deisgner Blocks for Gutenberg by Weaver"
3. Create a new page.
4. Insert a new "Image Columns" block. It can be found in the "Common Columns" group.
5. Change the columns in the options section on the right to two columns. This is the critical example that changes a value from the default.
6. Add a couple of images to the block. The rest doesn't matter.
7. Save the page, and then view it.
8. Now, re-open the page for editing. You should see the unexpected content error.
9. If you now examine the JS output via a browser dev tool (e.g., Firefox's), you can see the full validator output. If you use this example, then the output for the wrapping column class will show as 1 instead of the expected 2. The entire 'attributes' array has not been initialized to the new values.

The code defining this is in the /src/blocks/image-columns.js file.

The class is pretty much derived from the boilerplate generated by create-bguten-block. I don't know who is breaking the class initialization, but I suspect GB has done something.  

1. `node -v`: v8.11.2r
2. `npm -v`: 6.1.0
3. `yarn --version` (if you use Yarn):
4. `npm ls cgb-scripts` (if you haven’t ejected): gutenberg-image-blocks-cgb-guten-block@1.0.0 /Users/bw/Sites/wvrx.from-co.net/wp-content/plugins/blocks-by-weaver
└── cgb-scripts@1.9.7 

Then, specify:

1. Operating system: MacOS 10.13.6
2. Browser and version (if relevant):

**Possible Solution**

### Reproducible Demo

I think the steps describe above are as about as simple as possible.

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by ahmadawais** [comment]
Happy to receive a PR for this bug, I am spread way too thin nowadays?

**Comment by richtabor** [comment]
@weavertheme CGB is working fine on my end in Gutenberg 4.0+. There were a number of changes in Gutenberg all around that could throw errors. Do you have your project on GitHub by chance? I may be able to take a quick look under the hood tomorrow.

**Comment by ahmadawais** [comment]
Thanks for letting us know @richtabor I am closing this issue since the errors are not CGB related. @weavertheme make sure you're using the development version of Gutenberg to be able to read the errors.

**Comment by weavertheme** [comment]
Figured it out with some help. Seems to be caused by some internal change to Gutenberg with RichText.

Did need some RichText updating (not quite 100% parallel in edit and index), and had one attribute as a 'number' that was failing to update, but changing it to a 'string' fixed it.

The code had worked fine until GB 4.0, so they changed something.

**Comment by ahmadawais** [comment]
Nothing wrong with CGB :)
