### ISSUE TITLE
need example: block frontend loading/rendering

### ISSUE THREAD

**Issue by drzraf** [ahmadawais/create-guten-block#102]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'd like to understand the difference and implication of loading a block on editor versus loading it on the frontend. Current example blocks does not provide controls, like `InspectorControls`  from `wp.editor`.
Once a post is updated using the block, the next step is to **render** `$post['post_content']` on the frontend this time. IMO this is a missing bit from documentation and examples.

**Describe the solution you'd like**

It needs more example blocks having editor settings and being actually loaded, rendered and usable on the frontend too.

See also: https://wordpress.org/support/topic/gutenberg-react-block-frontend-rendering/

**Comment by ahmadawais** [comment]
I welcome a PR for this. 👍

**Comment by drzraf** [comment]
I feel bad... I still have no clue of how to render my block on the **frontend**.

**Comment by Jebble** [comment]
What do you mean with render your block on the front-end?

It's simply included in the post_content so every block renders automatically where you call the_content() in your loop.

Whatever you return in the save function of your block is what is saved to render on the front-end.

**Comment by drzraf** [comment]
Thank you!
