### ISSUE TITLE
Using wpack.io as build tool

### ISSUE THREAD

**Issue by swashata** [ahmadawais/create-guten-block#104]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Not really, but I believe it will inevitably solve #73	#102 etc.

**Describe the solution you'd like**

So right now, cgb uses it's own webpack implementation which works in this way (and please correct me here if I am wrong)

1. It looks for pre-defined files within the boilerplate.
2. On `npm start`, webpack is started in `watch` and `development` mode.
3. It compiles files to `dist`.
4. When file changes it does it again.

Here it is upto the user to reload browser to see the changes.

Also it would be a bit difficult to use the webpack setup for anything except for the predefined files.

**Describe alternatives you've considered**

I think, we can achieve much more, if cgb, were to, say relay the webpack thingy to [wpack.io](https://github.com/swashata/wp-webpack-script).

I am not going to bore you with more improvements that wpack.io can bring to the table, but I would like to know the feasibility first.

**The goods**

* Right now, everything that cgb provides, as first-class build solution, can be replaced by wpack.io with a little effort. We won't miss any functionality or feature here.
* We will get out of the box DX with any local WordPress server.
* Consumer can point out which files to assume an entry-point.
* Seamlessly add/remove entry-points.
* The entry-points could be some script to register gutenberg block or just some front-end/back-end script.
* I am not sure how cgb right now handles webpack [`output.publicPath`](https://webpack.js.org/configuration/output/#output-publicpath) for dynamic imports, and [`output.jsonpFunction`](https://webpack.js.org/configuration/output/#output-jsonpfunction) to avoid conflicts. But wpack.io does that effectively.

**The bad**

* A bit heavier `devDependency` for `cgb-scripts`.
* A new `dependency` `@wpackio/entrypoint` to make sure the dynamic imports work. This can be done during bootstrap, and consumers won't notice.
* No eject. Here I do feel a bit lost. I have written the whole tooling in typescript and provided many ways to extend and completely replace webpack and browser-sync config. So I never thought eject was needed.

**Teachability, Documentation, Adoption, Migration Strategy**

If you think this is possible, then in upcoming time, I would first replace a `cgb-scripts` generated block with `@wpackio/scripts`. You can review that and from there we can proceed to actually implement `@wpackio/scripts` within `cgb-scripts`.

Also do note that if you don't like/want the CLI styling of `wpackio-scripts`, then actually I can work a little to have it customizable. We can very much import node APIs from `@wpackio/scripts` and have it dressed anyway we want.

Let's make WordPress build tools awesome ✌️.

**Comment by ahmadawais** [comment]
For now, I am not interested in changing create-guten-block so dramatically. But yes, I am interested in having you as a contributor and maybe as a co-maintainer of the project in future. 

I have also had not looked at your repos, which is on my pending to do list. I am busy launching the [https://VSCode.pro/](https://VSCode.pro/) course next week. Then a personal project and then I'll try to find some support for this create-guten-block project. After that I'll reach out and ask you to see if you'll be interested in moving forward being in the same team of create-guten-block maintainers. 

So, for now, let's close this and revisit later. Till I get back to you, I'll really appreciate if you can start improving create-guten-block by contributing things in this repo without adding major dependencies. 

You're doing good work @swashata keep it up.
Peace! ✌️

**Comment by ahmadawais** [comment]
Also, there's a reason to keep create-guten-block options-less. It is explained in the README.md file under philosophy, so for now adding configurable features to CGB is pretty much not what I am looking for.

**Comment by ahmadawais** [comment]
@swashata my priority right now is the Hot Module Reloading. See if you can add that to create-guten-block and then we can talk about rolling you in as a maintainer 👍
