### ISSUE TITLE
Styles not working on latest Wordpress version (beta 5)

### ISSUE THREAD

**Issue by HelaGone** [ahmadawais/create-guten-block#107]
## Bug Report
I've been testing the latest version of Wordpress (beta 5) but when it comes to test the create-guten-block toolkit with this release, I notice that, in the front-end, the stylesheet isn't loaded and therefore that block styles are not rendered. 
I've followed the very same instructions to create a Gutenberg block and also I've tested the example block that comes with it and this behavior persist. 
I wonder if it has something to do with the enqueue function or maybe something else. 
I've been poking around in the init.php file in order to get this to work with no luck.
However, the toolkit works fine with the Gutenberg plugin and it renders the styles for both, editor and front-end

### Expected Behavior
It is expected that the toolkit render the styles for both editor and front-end. Just like it does when it is used with gutenberg's plugin. 

### Actual Behavior
The stylesheet is not loaded in the front-end. Seems like the enqueue function is not working properly.   
This is how it looks in the editor:
<img width="868" alt="screen shot 2018-11-22 at 11 23 17" src="https://user-images.githubusercontent.com/5982932/48916765-3d1af400-ee49-11e8-9bcb-cbcc752f4735.png">

And this is how it looks in the front-end
<img width="788" alt="screen shot 2018-11-22 at 11 23 28" src="https://user-images.githubusercontent.com/5982932/48916782-5328b480-ee49-11e8-92f5-6c34d80c01f7.png">

I've verified and double checked the class and the fact that the plugin stylesheet is not loaded in the front-end
<img width="442" alt="screen shot 2018-11-22 at 11 27 12" src="https://user-images.githubusercontent.com/5982932/48916871-a995f300-ee49-11e8-9d35-f5d265e86ee6.png">

### Steps to Reproduce

You only need a fresh installation of the latest release of Wordpress 5.0 beta 5 which can be downloaded from this link: https://wordpress.org/news/2018/11/wordpress-5-0-beta-5/
and create a new block with create-guten-block toolkit.
(Write your steps here:)

1. Create a block with `npx create-guten-block my-block`
2. Activate the resulting plugin in the plugin's manager
3. Create a new post and insert the new block
4. Save / Publish the post and go to front-ed to see if your block is styled as expected

1. `node -v`: 8.10.0
2. `npm -v`: 6.4.1
3. `yarn --version` (if you use Yarn):
4. `npm ls cgb-scripts` (if you haven’t ejected): 1.11.1

Then, specify:

1. Operating system: Mac OSX High Sierra

**Possible Solution**

### Reproducible Demo

Since I'm working on a local environment, I can't share a Reproducible Demo.

**Comment by mario-neuhold** [comment]
Changing the dependency from `wp-blocks` to `wp-editor` in the enqueue function should make the css load again:

```
wp_enqueue_style(
	'adw_blocks-cgb-style-css', // Handle.
	plugins_url( 'dist/blocks.style.build.css', dirname( __FILE__ ) ), // Block style CSS.
	array( 'wp-editor' ) // Dependency to include the CSS after it.
	// filemtime( plugin_dir_path( __DIR__ ) . 'dist/blocks.style.build.css' ) // Version: filemtime — Gets file modification time.
);
```
Seems like there were some changes in Gutenberg components that moved dependencies between wp.blocks and wp.editor.

**Comment by ahmadawais** [comment]
@mario-neuhold that seems to be true. Can you send a PR for that?

**Comment by mario-neuhold** [comment]
@ahmadawais I'm trying to figure out why that changed, to see if the adaptions are neede somewhere else too. Happy to provide a PR later. Or do you prefer a quick PR just for this piece of code?

**Comment by ahmadawais** [comment]
@mario-neuhold Actually, I'm away focused on launching my [VSCode Power User Course](https://VSCode.pro/) — so can use all the help atm. There was also #106 see if this is related to that. I'd like for you to investigate and make a PR, the way you suggested. 👍

**Comment by raffjones** [comment]
I have found that just removing the dependency altogether also works and the styles display as they should on the front side. I am just wondering if there is any risk with that?

**Comment by maximebj** [comment]
Same here, All my plugins are broken. 

I will make a PR, but first I need to ask to someone close to the project, like Riad Benguela to confirm me this : 

For the main style :
`array( 'wp-editor' )`
for admin only style :
`array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-editor' )`
for admin js: 
`array( 'wp-edit-blocks' )`

I still don't know why the editor styles are loaded in front (just for logged user though) but it adds unnecessary stylesheet for now.

**Comment by lkraav** [comment]
Did this issue find a confirmed solution? All above lgtm.

**Comment by HelaGone** [comment]
On nov 23, 2018 I did comment that the solution proposed by @mario-neuhold was right. 
I'll close this topic since that was the right solution.

**Comment by kristabice** [comment]
Hello, I just tried with this new fix... However, I am still having the same issue. This didn't seem to fix it for my site. Is anyone else having this problem still?
