### ISSUE TITLE
Babel build system needs to choose one version

### ISSUE THREAD

**Issue by jameskhamil** [ahmadawais/create-guten-block#112]
You're using a combination of babel versions that will cause problems on some systems

```
		"babel-core": "^6.25.0",
		"babel-eslint": "^8.2.1",
		"babel-loader": "^7.1.1",
```

https://stackoverflow.com/a/49183337

Related:

https://github.com/ahmadawais/create-guten-block/issues/88

**Comment by ahmadawais** [comment]
I am not using that. All Babel packages being used are the ones that are compatible with Babel 6. StackOverflow link states a combination of Babel 7 and 6 packages. That's not the case here.
