### ISSUE TITLE
create-guten-block breaks Image Block "Media Library" button

### ISSUE THREAD

**Issue by ChrisBAshton** [ahmadawais/create-guten-block#128]
## Bug Report

When activating a plugin created with `create-guten-block`, the "Media Library" button disappears from the native Image block.

|Image block without create-guten-block|Image block WITH create-guten-block|
|----------------------------------------|--------------------------------------|
|<img width="476" alt="screen shot 2018-12-23 at 14 56 31" src="https://user-images.githubusercontent.com/5111927/50384881-61c1f000-06c3-11e9-8472-04e2a01d72b1.png">|<img width="467" alt="screen shot 2018-12-23 at 14 56 51" src="https://user-images.githubusercontent.com/5111927/50384883-65ee0d80-06c3-11e9-92b2-08c669302cb5.png">|

### Expected Behavior

The "Media Library" button should continue working regardless of any installed create-guten-block plugins.

### Steps to Reproduce

1. Create a create-guten-block plugin
2. Activate the plugin
3. Try adding an Image block to a post.

1. `node -v`: 10.3.0
2. `npm -v`: 6.1.0
3. `yarn --version` (if you use Yarn): N/A
4. `npm ls cgb-scripts` (if you haven’t ejected): `cgb-scripts@1.13.0`

Then, specify:

1. Operating system: OSX
2. Browser and version (if relevant): N/A

**Possible Solution**

I've narrowed it down to this line:

https://github.com/ahmadawais/create-guten-block/blob/master/packages/cgb-scripts/template/src/init.php#L49

If you pass an empty dependencies array to the `wp_enqueue_script` function, the Image block continues to work as normal (though of course, the create-guten-block plugin itself breaks as a result!) 

### Reproducible Demo

https://github.com/ChrisBAshton/create-guten-block-debug

* ^ `git clone`, `npm install`, `npm start`
* Then upload the `dist/` folder and `plugin.php` to a subdirectory under Wordpress' `plugins/` directory.
* Go to a new or old post and try adding an Image block - should see Media Library option.
* Now activate the plugin, and try adding an Image block - the Media Library button is missing.

**Comment by ahmadawais** [comment]
It looks like that this is an issue with Gutenberg and not with create-guten-block. I see that you've already reported it there. I'll follow along the conversation there. Or else if it's create-guten-block — I am happy to accept a PR for this.

**Comment by ChrisBAshton** [comment]
> I see that you've already reported it there

Not quite, I just commented on an issue which had the same symptom (but a different cause: outdated ACF plugin), in the hope it would be useful to people in future.

That said, if you think this is an issue with Gutenberg rather than create-guten-block, I'm happy to raise an issue there. Have raised: https://github.com/WordPress/gutenberg/issues/13084

**Comment by ahmadawais** [comment]
Feel free to debug it and send a PR. I've limited access to the internet while on vacations. 👍 

Will look more deeply into this when I get back to work next year.
