### ISSUE TITLE
npm start Error

### ISSUE THREAD

**Issue by ivcreative** [ahmadawais/create-guten-block#129]
System:

Windows 10

VM: Vagrant scotchboxpro (Ubuntu 17.10)
Node version: 8.9.4
NPM version: 5.7.1

When trying to do npm start I get the following error:

```
> cgb-scripts start

sh: 1: cgb-scripts: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
```
I have also tried running it with sudo same error

**Comment by ahmadawais** [comment]
That's a permission error of your OS unrelated to create-guten-block. The fix I have heard is reinstalling npm again and updating it to the latest version. Dig through the issue many Windows users reported stuff like this — I don't use Windows so can't help further than that.
