### ISSUE TITLE
How is JS linting supposed to work?

### ISSUE THREAD

**Issue by kmgalanakis** [ahmadawais/create-guten-block#134]
I'm using the `create-guten-block` toolkit.

I intentionally made a few JS mistakes that the JS linting with ESLint would normally catch, while developing my block and having `npm start` to run in the background, but I don't see any linting errors in my console.

Browsing the scripts code, in the `dev` webpack config, I don't see any loaders related to ESlint.

So how JS linting using ESLing is working in `create-guten-block`?

**Comment by ahmadawais** [comment]
ESLint files are just baked in but they should work if you set it up on your own. E.g. I set it up in VSCode. I have not added a strong checking for everyone since ESLint rules for WordPress are not really a standard WP follows.
