### ISSUE TITLE
Include package from node_module in Webpack

### ISSUE THREAD

**Issue by tyrann0us** [ahmadawais/create-guten-block#139]
I was wondering if it's somehow possible to let Webpack include packages that are manually added to the plugin. The specific case concerns https://github.com/vermiliondesign/gutenberg-post-selector that can't be used if installed with `npm` because it doesn't contain bundled files (https://github.com/vermiliondesign/gutenberg-post-selector/issues/2).

Any feedback appreciated. Thanks!

**Comment by ahmadawais** [comment]
Should be manually required in a JS file that's being processed by webpack. Also, not related to this repo, you should probably checkout how webpack works.
