### ISSUE TITLE
Each plugin includes node_modules directory

### ISSUE THREAD

**Issue by dev4press** [ahmadawais/create-guten-block#145]
I tried the Create Guten Block for the first time, and when I run it, it creates new plugin folder for the block, but, in each instance it adds node_modules directory to each created plugin and each time this directory is 60MB+. The directory structure for the created plugin doesn't mention that this will happen,

Why are all NPM packages added to each plugin created, and not added to the global NPM package store? Is there something in the installation process that needs to be done?

I use Windows 10 Pro (64bit) with Node 10 (recommended installation from Node website).

**Comment by ahmadawais** [comment]
You probably need to learn how the Node.js eco-system works. :) 

Also checkout the multi blocks example. You don't need to run it again for new blocks in the same plugin https://github.com/ahmadawais/create-guten-block/tree/master/examples
