### ISSUE TITLE
Unable to run create-guten-block in Apache directory

### ISSUE THREAD

**Issue by LensDigitial** [ahmadawais/create-guten-block#146]
I can run create-guten-block in my home directory;

`
📦   Creating a WP Gutenberg Block plugin called:  testblock

 In the directory: /home/andrewspiers/testblock
 This might take a couple of minutes.

✔ 1. Creating the plugin directory called →  testblock
✔ 2. Installing npm packages...
✔ 3. Creating plugin files...

✅   All done! Go build some Gutenberg blocks.

CGB (create-guten-block) has created a WordPress plugin called  testblock  that you can use with zero configurations #0CJS to build Gutenberg blocks with ESNext (i.e. ES6/7/8), React.js, JSX, Webpack, ESLint, etc.

Created testblock plugin at: /home/andrewspiers/testblock
`
However, when I run the same command in the Apache directory (/var/www/html/wp-content/plugins). I get the following error;

`📦   Creating a WP Gutenberg Block plugin called:  testblock

 In the directory: /var/www/html/wp-content/plugins/testblock
 This might take a couple of minutes.

⠋ 1. Creating the plugin directory called →  testblock mkdir: cannot create directory testblock: Permission denied
cd: no such file or directory: /var/www/html/wp-content/plugins/testblock
/usr/local/lib/node_modules/create-guten-block/index.js:60
        throw err;
        ^

ShellJSInternalError: EACCES: permission denied, open '.gitignore'
    at Object.fs.openSync (fs.js:663:18)
    at touchFile (/usr/local/lib/node_modules/create-guten-block/node_modules/shelljs/src/touch.js:68:19)
    at /usr/local/lib/node_modules/create-guten-block/node_modules/shelljs/src/touch.js:47:5
    at Array.forEach (<anonymous>)
    at Object._touch (/usr/local/lib/node_modules/create-guten-block/node_modules/shelljs/src/touch.js:46:9)
    at Object.touch (/usr/local/lib/node_modules/create-guten-block/node_modules/shelljs/src/common.js:384:25)
    at module.exports (/usr/local/lib/node_modules/create-guten-block/app/createGitignore.js:13:8)
    at Promise (/usr/local/lib/node_modules/create-guten-block/app/createPluginDir.js:47:10)
    at new Promise (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/create-guten-block/app/createPluginDir.js:44:10)
`

The command run in both circumstances is "create-guten-block testblock"

**Comment by ahmadawais** [comment]
Looks like a permission error. Did you try with `sudo npx create-guten-block testblock`? Looks like your OS is stopping the creation of `'.gitignore` file.

**Comment by LensDigitial** [comment]
That just throws a different error;

`⠴ 2. Installing npm packages.../usr/local/lib/node_modules/create-guten-block/index.js:60
        throw err;
        ^

Error: Command failed: npm install cgb-scripts --save --save-exact --slient
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
Unable to save binary /var/www/html/wp-content/plugins/testblock/node_modules/node-sass/vendor/linux-ia32-59 : { Error: EACCES: permission denied, mkdir '/var/www/html/wp-content/plugins/testblock/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:905:18)
    at sync (/var/www/html/wp-content/plugins/testblock/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/var/www/html/wp-content/plugins/testblock/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/var/www/html/wp-content/plugins/testblock/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/var/www/html/wp-content/plugins/testblock/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/var/www/html/wp-content/plugins/testblock/node_modules/node-sass/vendor' }
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/var/www/html/wp-content/plugins/testblock/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@9.1.0 | linux | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 9.1.0
gyp verb command install [ '9.1.0' ]
gyp verb install input version string "9.1.0"
gyp verb install installing version: 9.1.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 9.1.0
gyp verb build dir attempting to create "build" dir: /var/www/html/wp-content/plugins/testblock/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/html/wp-content/plugins/testblock/node_modules/node-sass/build'
gyp ERR! System Linux 4.15.0-45-generic
gyp ERR! command "/usr/local/bin/node" "/var/www/html/wp-content/plugins/testblock/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/wp-content/plugins/testblock/node_modules/node-sass
gyp ERR! node -v v9.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andrewspiers/.npm/_logs/2019-02-10T14_50_10_565Z-debug.log


> node-sass@4.11.0 install /var/www/html/wp-content/plugins/testblock/node_modules/node-sass
> node scripts/install.js


> uglifyjs-webpack-plugin@0.4.6 postinstall /var/www/html/wp-content/plugins/testblock/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.11.0 postinstall /var/www/html/wp-content/plugins/testblock/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /var/www/html/wp-content/plugins/testblock/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=

    at makeError (/usr/local/lib/node_modules/create-guten-block/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/create-guten-block/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`
I agree that it is a permissions error. I have tried adding my user to the www-data group but that didn't work either.

**Comment by LensDigitial** [comment]
Fixed with;

sudo chown -R $USER /var/www/html

**Comment by ahmadawais** [comment]
Glad to see you fixed it. It was a permission issue.

**Comment by kmasalam** [comment]
Some One Help me I am Facing issue with npx create-guten-block my-block . Because whenever i am going run it on my plugin directory it throws me error. I am using windows 10

F:\Server\htdocs\test1\wp-content\plugins>npx create-guten-block my-block
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Salam\AppData\Roaming\npm-cache\_npx\11964" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abdus Salam\AppData\Roaming\npm-cache\_logs\2020-01-05T04_47_18_038Z-debug.log
Install for [ 'create-guten-block@latest' ] failed with code 1

**Comment by fedegonzal** [comment]
Hi had the same problem, solved changing to the node v14.17.0 version
