### ISSUE TITLE
Plugin Sidebar

### ISSUE THREAD

**Issue by megphillips91** [ahmadawais/create-guten-block#153]
For my plugin, I needed to add sidebar for meta-data and other fields that I need to save associated at the post/page level. This may be obvious to others, but I spent a couple hours in the WP Docs and other tutorials before realizing that adding a sidebar to my custom block code which was created with create-guten-block was a simple 3-step process as follows. 

--  add new dependencies within init.php wp_enqueue_script
-- import my sidebar.js file within blocks.js
-- create and save sidebar markup

Maybe outline that in your readme information because how seamlessly a sidebar can be created makes your create-guten-block super complete and fantastic.

**Comment by ahmadawais** [comment]
Honestly, CGB is quite powerful and not that opinionated. Glad to see people making the most out of it.

**Comment by megphillips91** [comment]
You deserve that award my friend. You've got my vote (if I had one ;) )
