### ISSUE TITLE
Generated block doesn't appear in the editor

### ISSUE THREAD

**Issue by stephensauceda** [ahmadawais/create-guten-block#156]
## Bug Report
Generated block doesn't appear in the editor in new blocks I've created today. Previous blocks I've created (as current as last week) worked fine.

I see the script and styles being included on the post editor page, but the block itself does not appear in the block selector. There are no errors in the browser console.

### Expected Behavior
After generating a new block and activating the subsequent plugin, the new block should be available in the WordPress editor immediately.

### Actual Behavior
The block does not appear in the WordPress editor's block selector.

### Steps to Reproduce
1. `npx create-guten-block my-new-block`
2. Activate plugin in WordPress admin
3. Go to WordPress post editor
4. The new block is not present in the block selector

1. `node -v`: v10.13.0
2. `npm -v`: 6.4.1
3. `yarn --version` (if you use Yarn):
4. `npm ls cgb-scripts` (if you haven’t ejected): 1.17.0 

Then, specify:

1. Operating system: OSX 10.14

**Comment by ahmadawais** [comment]
I just tested this and everything's working fine. The new block created is searchable and it works. I am pretty sure that there's another problem through some other plugin in your case. Disable all plugins and try.

**Comment by ahmadawais** [comment]
Run `npx create-guten-block -d` in the same repo.

This is my env

```

Environment:
  OS: macOS XXXX
  CPU: x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Node: 10.11.0
  Yarn: 1.13.0
  npm: 6.9.0
  Watchman: Not Found

Browsers:
  Chrome: 73.0.3683.86
  Chrome Canary: Not Found
  Firefox: 65.0.1
  Firefox Developer Edition: 57.0
  Firefox Nightly: Not Found
  Safari: 11.1.1
  Safari Technology Preview: Not Found

Packages: (wanted => installed)
  cgb-scripts: 1.17.0 => 1.17.0

```

**Comment by DominicTobias** [comment]
@stephensauceda did you figure out why?

**Comment by stephensauceda** [comment]
I did. But since it’s been seven months I don’t remember what it was.

**Comment by DominicTobias** [comment]
All good I copied a block which had `parent` specified, since both had parent they weren't showing up
