### ISSUE TITLE
Editing The gutenblock

### ISSUE THREAD

**Issue by brothman01** [ahmadawais/create-guten-block#160]
I must be using the block boilerplate incorrectly....

I have copied "01-single-block" from the examples folder to my plugins folder, and done the following:
1. `cd 01-single-block`
2. `npm start`
3. Make changes in the file `01-single-block/src/block/block.js`
4. `^c`
5. `npm run build`
but the changes I make in block.js do not appear on the page using the block.  What am I doing wrong?

**Comment by ahmadawais** [comment]
Examples are old and outdated. Read the docs and build a new block for your plugin instead of copying from the examples. 

And if that doesn't work file a bug report answering all the questions asked.
