### ISSUE TITLE
How to add file-loader?

### ISSUE THREAD

**Issue by mathishuettl** [ahmadawais/create-guten-block#198]
Hello,

how can i correctly add file-loader? I cant find a webpack.conf or something when i hit npx create-guten-block.

My aim is to import a png file with
 import myfile from "./images/test.png"

**Comment by ahmadawais** [comment]
You can do that in a JS file and it should work. Otherwise, just eject.

**Comment by mathishuettl** [comment]
i ejected, but since i did that arrow-functions doesnt work anymore.. 
![Unbenannt](https://user-images.githubusercontent.com/9340538/61113403-824e6d80-a48e-11e9-9645-688fff5ef73c.PNG)

**Comment by juanRabaa** [comment]
> You can do that in a JS file and it should work. Otherwise, just eject.

@ahmadawais  I can't import images on a clean project using `import './img.png`. Do I need anything else? I don't see a webpack config file to set up a loader.
![image](https://user-images.githubusercontent.com/28640722/71169951-e98bfd00-2238-11ea-8e8a-e139d8624262.png)

**Comment by therajuahammad** [comment]
> > You can do that in a JS file and it should work. Otherwise, just eject.
> 
> @ahmadawais I can't import images on a clean project using `import './img.png`. Do I need anything else? I don't see a webpack config file to set up a loader.
> ![image](https://user-images.githubusercontent.com/28640722/71169951-e98bfd00-2238-11ea-8e8a-e139d8624262.png)

I'm also facing this problem.
