### ISSUE TITLE
Including classnames Package

### ISSUE THREAD

**Issue by HardeepAsrani** [ahmadawais/create-guten-block#20]
### Is this a bug report?

No, feature request.

Are we going to include classnames library so people can have multiple classes in their blocks? https://github.com/JedWatson/classnames

@ahmadawais

**Comment by ahmadawais** [comment]
@HardeepAsrani Thanks for reaching out. I think that this package is too focused and not everyone would need that. So, anyone who does can always install it after create-guten-block has run. 👍 

We might reiterate over this in future though.
