### ISSUE TITLE
Some problem with radium library

### ISSUE THREAD

**Issue by NasKadir123** [ahmadawais/create-guten-block#205]
Hi!
I'm actually a newbie, so sorry for this question.
I can't install radium library for this webpack, I have something like this in terminal:
npm WARN babel-plugin-styled-components@1.10.6 requires a peer of styled-components@>= 2 but none is installed. You must install peer dependencies yourself.
npm WARN react-bounds@0.3.1 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.

Then I'm trying to install styled-components and have the same warn.
What should I do?
I used radium for my react app and everything was fine.
I need this lib to manage inline styles on some elements.
Can you help me, please?

**Comment by thatwpdeveloper** [comment]
Did you manage to solve this, @NasKadir123 ?
