### ISSUE TITLE
Status: Babel 7 webpack 4 package updates

### ISSUE THREAD

**Issue by niklasp** [ahmadawais/create-guten-block#237]
I am seeing lots of pull requests concerning babel and webpack 4 updates. I need these to run the `@wordpress/scripts` tests. What is the status. What is the problem with the merge requests. How can we get `create-guten-block` to support these versions? @ahmadawais

**Comment by ahmadawais** [comment]
The problem is I am a single Developer with almost zero support on this project. I have bills to pay and other work. If you can help review and make it better you are most welcomed otherwise you'll have to wait for me to get free.
