### ISSUE TITLE
Adding package classnames for supporting multiple classnames? (Consideration)

### ISSUE THREAD

**Issue by igorbenic** [ahmadawais/create-guten-block#25]
Was just working on a test block and I've found that I needed to install the classnames (not supported by default).

I guess that won't be always needed but since different states of a block could be represented with different classes, it might be useful to have it in?

Package: https://www.npmjs.com/package/classnames

It's not a problem to install it by hand of course but if most people find it a good thing to have, it might be considered to be included in a near future?

**Comment by ahmadawais** [comment]
Duplicate #20 
@igorbenic 
Thanks for reaching out. I think that this package is too focused and not everyone would need that. So, anyone who does can always install it after create-guten-block has run. 👍

We might reiterate over this in future though.

**Comment by igorbenic** [comment]
Thanks for such a fast reply.

Yes, it is really easy to add that package if you need it :)
