### ISSUE TITLE
Loading backend styles in frontend: Unusable with Gutenberg 7.5 AND performance/GDPR issue

### ISSUE THREAD

**Issue by mariohamann** [ahmadawais/create-guten-block#268]
1. I created a completely clean WordPress-Website.
2. I created a new block with create-guten-block: It loads all backend styles. -> **Performance problem. Even a Google font style is being loaded and that's a real problem for GDPR.**
3. I installed Gutenberg 7.5: Backend styles are loaded and there is a new backend-style for mobile devices:
```
html {
    position: fixed;
    width: 100%;
}
```
-> **EVERY website with create-guten-block and Gutenberg 7.5 can't be scrolled on mobile**

**Without cgb-block:**
![without-block-suite](https://user-images.githubusercontent.com/26542182/74512464-9a94d800-4f08-11ea-9b05-d395fe8ca4ef.png)

**With cgb-block**
![with-block-suite](https://user-images.githubusercontent.com/26542182/74512453-94066080-4f08-11ea-9ef5-85ad605ffd8a.png)

I can confirm for every website, every theme and every block I created with cgb and with Gutenberg 7.5.
Issue in Gutenberg github: https://github.com/WordPress/gutenberg/issues/20214

**Comment by ahmadawais** [comment]
CGB gives you the code, you can edit all of it. If you can improve it, send in a PR. @asharirfan look into this.

**Comment by mariohamann** [comment]
I think it seems to relate to #210 and #267.  (Didn't see it earlier, I'm sorry.)

**Comment by ahmadawais** [comment]
This issue must have been solved via #267. 

Successfully published:
 - cgb-scripts@1.23.0
 - create-guten-block@1.14.0

You do have to manually update the [init.php file like this](https://github.com/ahmadawais/create-guten-block/pull/267/files).
