### ISSUE TITLE
Warn if chosen name starts with a number

### ISSUE THREAD

**Issue by helen** [ahmadawais/create-guten-block#28]
I, of course, tested this using `10up-blocks` as the name and it fataled, because PHP functions (and CSS class names) cannot begin with numbers. I would expect the generator to yell at me rather than creating a non-functional plugin.

More broadly, I think any passed arguments should be validated wherever they're not yet, and I think it may make more sense to have a separate namespacing argument especially once getting into the multi-block thing. PHP namespacing would make a lot of sense too, IMO :) Related, for prompts: #26 

I haven't tested to see if the initializer warns about anything besides an empty name, but it's possible/likely that this applies to starting with any invalid character or really containing anything besides `[A-Z0-9-_]`.

**Comment by ahmadawais** [comment]
Hey, @helen 🙌

It's awesome to see you trying out `create-guten-block`. 

>I, of course, tested this using 10up-blocks as the name and it fataled, because PHP functions (and CSS class names) cannot begin with numbers. I would expect the generator to yell at me rather than creating a non-functional plugin.

Yeah, why didn't I think of that earlier?! This should be handled in the next release. Would you be interested in submitting a PR? I think this should be addressed early on in the cli.js file...

https://github.com/ahmadawais/create-guten-block/blob/39c83b445921e506b07ae364fe14ac23809afe54/packages/create-guten-block/app/cli.js#L50-L54

↑ That's where I format the name and use all over the place. 💯 

>More broadly, I think any passed arguments should be validated wherever they're not yet, and I think it may make more sense to have a separate namespacing argument especially once getting into the multi-block thing. PHP namespacing would make a lot of sense too, IMO :) Related, for prompts: #26

🤔 While PHP namespacing works, I didn't want to overcomplicate PHP for devs that are coming from non-php world to WordPress — to try an build Gutenberg stuff. But I see that now it should be a viable option to use PHP OOP for this stuff. Not sure if it will make things better or complex for devs who are accustomed to writing PHP functions.

Suggestions?

>Related, for prompts: #26

Taking time to think about if we need that or not. It's really easy to cook that in, I just don't want to make this zero-config kit have lots of options, in favor of sane defaults. 

>I haven't tested to see if the initializer warns about anything besides an empty name, but it's possible/likely that this applies to starting with any invalid character or really containing anything besides [A-Z0-9-_].

Right about that as well. Right now, this is what I have 
https://github.com/ahmadawais/create-guten-block/blob/39c83b445921e506b07ae364fe14ac23809afe54/packages/create-guten-block/app/cli.js#L40

This can be improved a lot. Care to submit a PR? 

Peace! ✌️

**Comment by ahmadawais** [comment]
Thanks to @wpjsio this issue has now been fixed. Tests are welcomed.
