### ISSUE TITLE
Missing instructions / command for global install in readme

### ISSUE THREAD

**Issue by DavidAPowers** [ahmadawais/create-guten-block#283]
Hi, just a note that your readme is a bit confusing, Step 1 just skips over the step of installing create-guten-block globally:
``npm install create-guten-block --global``

This could be very confusing for a newbie!

Also, on a related note, I believe the instructions are also slightly messed up under Step 1 & 2 on this page: https://ahmadawais.com/create-guten-block-toolkit/

In Step 1 The line ``npx create-guten-block my-block``
should be: ``npm install create-guten-block --global``

And to avoid confusion, In Step 2 the line: ``create-guten-block my-block``
Should probably be: ``npx create-guten-block my-block``

**Comment by stephensauceda** [comment]
`npx create-guten-block my-block` is the correct first step because you _don't have to_ install the tool globally with `npx`. `npx` exists specifically so you don't have to install packages globally.

**Comment by ahmadawais** [comment]
I don't recommend global installs. That's why. Try reading what's written there about npx. It's an actual first step. 😆
