### ISSUE TITLE
Remove 'className={ props.className }' from 'save' function

### ISSUE THREAD

**Issue by dgwyer** [ahmadawais/create-guten-block#29]
Currently `props.className` is undefined in the `save` function so `className={ props.className }` should probably be removed until it is supported.

**Comment by ahmadawais** [comment]
@dgwyer At the time I was building it, that was supported. Which version of Gutenberg are you using, can you share how to reproduce this error.

**Comment by dgwyer** [comment]
The CSS class name is applied to the top level element in `save` by default. So the `className={ props.className }` attribute isn't necessary.

In fact if you try to output props this is what's outputted:

![gb-props](https://user-images.githubusercontent.com/1482075/36039406-4e255bc0-0dba-11e8-8943-acebc06bf25e.png)

As you can see there is no `props.className` property. Are you seeing something different?

**Comment by abdullah1908** [comment]
@ahmadawais I'll surely try this :)

**Comment by ahmadawais** [comment]
@abdullah1908 sure. It's a good first issue for a new contributor like you.

Make sure you read the Contributing.md file and follow the AA Git Commit Log.


### 🌟 Always use AA Git Commit Log Messages

What is that? I like emoji and I have invented a way to keep the git log clean and simple. Read this [AA Git Commit Log](https://gist.github.com/ahmadawais/815ea20134cf4616a6b2a965eb08f716) to learn more.
