### ISSUE TITLE
Multiple Blocks

### ISSUE THREAD

**Issue by sharazghouri** [ahmadawais/create-guten-block#30]
### Is this a bug report?

(Write your answer here.)

  I want to create multiple blocks with "create-guten-block ". Is right  approach to code for multiple blocks write in single file  "src/block/block.js".  Here the best thing found 👍  eslint configuration which not ship with other one environment. 
### Environment

1. `node -v`:
2. `npm -v`:
3. `yarn --version` (if you use Yarn):
4. `npm ls cgb-scripts` (if you haven’t ejected):

Then, specify:

1. Operating system:
2. Browser and version (if relevant):

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by ahmadawais** [comment]
Hey, @sharazghouri!

Take a look at the [examples](https://github.com/ahmadawais/create-guten-block/tree/master/examples) and their README.md files to see how easy it is to create a mulitple set of blocks in one single plugin. 

Also we are trying to pin down an approach to automate it in #18
