### ISSUE TITLE
Remove eval'ed code on production build

### ISSUE THREAD

**Issue by bfintal** [ahmadawais/create-guten-block#35]
This is in the production build configuration:

```devtool: 'cheap-eval-source-map'```

and produces eval'ed code in the built JS files.

This is okay with development, but should not be present in the production builds.

**Comment by ahmadawais** [comment]
@bfintal May I ask why? Sourcemaps are great both in production and dev but you can disable them by creating a `env` file with `GENERATE_SOURCEMAP` set to false.

I suppose devtool will get disabled by that as well. But correct me if I am wrong.

**Comment by bfintal** [comment]
As I recall, i tried turning off generate sourcemap earlier, but it still added in eval code in the JS. It’s only when i removed devtool that those went away.

The reason for my suggestion is that the WP plugin directory doesn’t allow eval’ed base64 JS code

**Comment by ahmadawais** [comment]
That makes sense. For now I am making generation of source-maps optional via `env` file with `GENERATE_SOURCEMAP` set to true.

Releasing a new version in a few minutes.

**Comment by ahmadawais** [comment]
This should be now fixed in `cgb-scripts` 1.9.5. Can you test it for me and report back? @bfintal

**Comment by ahmadawais** [comment]
Just run the same command again and you'll get the latest `cgb-scripts` or manually update it's version.

**Comment by bfintal** [comment]
@ahmadawais Thanks!

I can confirm that the base64 js code is no longer there in `npm run build` at 1.9.5

Does CGB accept `.env` during the start or build scripts? it doesn't seem to read the file. I can set the env variable though by changing my `build` script in `package.json` to:

    "build": "cross-env GENERATE_SOURCEMAP=true cgb-scripts build",

**Comment by ahmadawais** [comment]
@bfintal I have been cooking the `.env`based customization possibility inside this project it's not ready and not tested at the moment. Feel free to jump in and contribute at #11
