### ISSUE TITLE
Node v 8 or higher is required

### ISSUE THREAD

**Issue by barbareshet** [ahmadawais/create-guten-block#39]
I know you have an npm version too, but if someone wants to use the npx option, I think it will be good to mention the requirements (npm & node required versions).
Sorry for not labeling, could't find this option

**Comment by ahmadawais** [comment]
I have mentioned it there in the Step # 0 👍 take a look. But I'll mention it with other steps as well.

![image](http://on.ahmda.ws/q9qZ/c)

**Comment by ahmadawais** [comment]
Actually, I just saw, it is mentioned there.

![image](http://on.ahmda.ws/q8ur/c)

**Comment by barbareshet** [comment]
Thanks,
Found it later.
