### ISSUE TITLE
Can I Use Single Stylesheet with create-guten-block?!

### ISSUE THREAD

**Issue by DannyCooper** [ahmadawais/create-guten-block#42]
When using the same styles on the front and backend, is there a way to have just one stylesheet, rather than repeating the code between the editor.scss and style.scss?

**Comment by EpicWebs** [comment]
The stylesheets are enqueued inside the init.php file. You could just point them both to the same file if you'd like.

**Comment by ahmadawais** [comment]
@DannyCooper Yes. That's what `style.css` is. Read the `init.php` file https://github.com/ahmadawais/create-guten-block/blob/master/examples/01-single-block/src/init.php#L16-L34

Also, thanks @EpicWebs for helping out with the issues. Keep at it.
