### ISSUE TITLE
Why is my eslint throwing this

### ISSUE THREAD

**Issue by HasnainAshfaq** [ahmadawais/create-guten-block#45]
I've checked my eslint, uninstalled and reinstalled it but whenever I create a new block I get this.

**Missing JSDoc @returns for function. (valid-jsdoc)**

**Comment by ahmadawais** [comment]
It's coz the ESLintRC is set for that https://github.com/ahmadawais/create-guten-block/blob/master/packages/cgb-scripts/template/.eslintrc.json#L188

It was fixed by adding docs in #46 — I'll push a new create-guten-block update soon.

**Comment by smlombardi** [comment]
I'm still seeing this error.
