### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by strarsis** [ahmadawais/create-guten-block#53]
Using code from Gutenberg core blocks I get an import error:
```js
/**
 * WordPress dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { PanelBody, RangeControl } from '@wordpress/components';
import { Fragment } from '@wordpress/element';
import {
	InspectorControls,
	InnerBlocks,
} from '@wordpress/blocks';
````

````
Uncaught Error: Cannot find module "@wordpress/i18n"
````
How can I use these dependencies (from `@wordpress`)? 
Do I have to install a package first? Configure webpack differently?

(Issue originally created in deprecated repository, see https://github.com/ahmadawais/Gutenberg-Boilerplate/issues/23#event-1611342380)

**Comment by ahmadawais** [comment]
I am not sure if this is related to this repository. Also you ignored the new issue template so I don't know anything about what you used and what you didn't. Closing it!
