### ISSUE TITLE
[Question] How to import from Gutenberg core components?

### ISSUE THREAD

**Issue by strarsis** [ahmadawais/create-guten-block#54]
I want to import core components from Gutenberg like `Fragment` or `InnerBlocks`.
The Gutenblock should be able to hold other blocks (nestable), I am trying to use the code of Columns block for allowing this: https://github.com/WordPress/gutenberg/blob/master/core-blocks/columns/index.js.
`import { PanelBody, RangeControl } from '@wordpress/components'; `

However, the import fails as `@wordpress` is imported and cannot be found (`Uncaught Error: Cannot find module "@wordpress/i18n"`). Do I have to use a different name for importing from `@wordpress`?

This is not a bug in `create-guten-block`, I am probably just importing incorrectly.

**Comment by zackify** [comment]
You can do `const { PanelBody } = wp.components`

They are available on the window when inside of the gutenberg editor!

![image](https://user-images.githubusercontent.com/449136/39667929-1532542c-508f-11e8-9863-c651c43e773a.png)

**Comment by strarsis** [comment]
Thanks!
