### ISSUE TITLE
Move the init.php file into the dist folder

### ISSUE THREAD

**Issue by gubbigubbi** [ahmadawais/create-guten-block#57]
## Feature Request

I really like the way there is a dist folder at the moment, it makes it super easy to update all of clients folders (my plugin isnt ready for release yet so when I make changes I just resync the dist folders on my clients servers).

Ideally I wouldnt push the 'src' folder to my clients sites though (or to the plugin repo) but at the moment the init.php is in the src folder. If this was places in the dist folder or even just in the root folder it would be much better for updates.

**Comment by ahmadawais** [comment]
I see what you're saying here but for that you need to create an extra layer of task that creates a plugin for you by placing init.php in the desired folder. In its current form create-guten-block is meant to have both the `src` and `dest` folders inside the plugin.

Closing it for now, I'll think about adding another task called `npm run package` where this can happen. Happy to accept a PR.
