### ISSUE TITLE
Add react  svg loader

### ISSUE THREAD

**Issue by ERROPiX** [ahmadawais/create-guten-block#61]
Any chance to add react-svg-loader to allow loading custom svg icons for blocks?

**Comment by ahmadawais** [comment]
You can do that by yourself after creating a block with create-guten-block. 👍

**Comment by ERROPiX** [comment]
I have installed react-svg-loader via npm but on running npm start, I get error that moule react-svg-loader not found

I think it's better to get that integrated into the cgb-scripts

**Comment by ahmadawais** [comment]
Pretty sure it's not related to cgb-scripts. Will find some time to investigate.

**Comment by braco** [comment]
Agree with @ERROPiX, this would be a good default and SVG can be inlined.
