### ISSUE TITLE
Alignment Toolbars

### ISSUE THREAD

**Issue by weavertheme** [ahmadawais/create-guten-block#63]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Since both the block and content alignments have become "standard" for many of the native blocks, it would be nice if the original template of the create-guten-block initial build would include the toolbars, along with the current elements created.

Right now it is pretty easy to create many blocks with the current template, but I found adding the alighment toolbars quite difficult to figure out.

**Comment by ahmadawais** [comment]
The purpose of this Starter Kit is to get you started and not provide a lot of boilerplate code. What you're looking for is what goes in the examples folder of this repo. Maybe send in a PR and I'll add it there :)
