### ISSUE TITLE
Add a .gitignore file to the generated plugin

### ISSUE THREAD

**Issue by salcode** [ahmadawais/create-guten-block#66]
## Feature Request

**Is your feature request related to a problem? Please describe.**

When I created a Git repo for my first block, the files from `./node_modules` where included when I ran `$ git add .`

In my experience, `./node_modules` is generally excluded from project repos.

**Describe the solution you'd like**

I would like to see a default `.gitingore` file included when a block plugin is generated.  Specifically, I would like to see `node_modules` list in this new file.

I don't see a downside to this change.

**Describe alternatives you've considered**

I've also considered excluding the `./dist` folder.  Personally, on my projects I prefer to exclude folders like this (that contain generated code).

However, this would have the downside that if someone cloned the repository, the plugin would not work until after they ran `npm`.  I still think it would make sense to add the `./dist` folder but I can see why one might choose not to.

**Teachability, Documentation, Adoption, Migration Strategy**

I don't see any of this as necessary for excluding `./node_modules`.

If it is decided to exclude `./dist`, it would be helpful to include documentation in the generated `README.md` that indicates the plugin will **not** work unless `npm start` or `npm run build` is executed first.

**Comment by ahmadawais** [comment]
Actually, I do have a `.gitignore` [file](https://github.com/ahmadawais/create-guten-block/blob/master/packages/cgb-scripts/template/.gitignore) but it's hidden so it's not being copied. I think it'd be better if I generate it on the flow so that it's taken care of.

**Comment by ahmadawais** [comment]
BTW happy to accept PR for this. I'm spread way too thin nowadays.

**Comment by brianjohnhanna** [comment]
Merged via #90
