### ISSUE TITLE
Disable ESlint if prefer Prettier?

### ISSUE THREAD

**Issue by smlombardi** [ahmadawais/create-guten-block#69]
## Feature Request

I have my VSCode set up to use Prettier instead of ESlint.  Therefore the two of them are fighting it out over formatting and "errors."

For example, at work, we use 2 spaces instead of tabs and single quotes in our JS.  This is flagged as an error.

**Comment by ahmadawais** [comment]
Prettier is not WordPress standards compatible. So, I don't think we'll be letting go off of ESLint. Also, ESLint is a linter not just a formatter. You can remove the ESLint config if you'd like.
