### ISSUE TITLE
TEST: Environment information

### ISSUE THREAD

**Issue by dingo-d** [ahmadawais/create-guten-block#7]
Reporting the test environment for the package:

```sh
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 8.9.0
  Yarn: 0.24.6
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Not Found
  Android Studio: Not Found
```

The package seems to be working. Although I had to use `npx` to use it, so this should be noted as a possible troubleshoot.

Great work 💯

**Comment by ahmadawais** [comment]
@dingo-d 

That's very kind of you to say! 💯

Thanks for helping me test it. You might wanna look into `nv` since it is working for everyone else.

**Comment by dingo-d** [comment]
Yeah, could be something with globally exposing node.
