### ISSUE TITLE
I just had to share!

### ISSUE THREAD

**Issue by weavertheme** [ahmadawais/create-guten-block#70]
## Feature Request
Get more new GB blocks into the public's eye.

This really isn't a feature request or anything, but I'm working on a block add-on plugin, and just finished what I think is a very nice block. Really comes close to some page builder features.

I did manage to get a lot of exercising GB in the process, and found a few bugs, but I think GB is noticeably more stable than when I started on my projects a few months ago.

But, do have a look at this demo:
[All-in-One Image/Text Gutenberg Block](https://weavertheme.com/all-in-one-image-text-block-for-gutenberg-demo/)

**Describe the solution you'd like**
Thanks for looking. Sorry to go a bit off topic, but I think as more folks contribute good new blocks, people will be able to understand what Gutenberg is all about.

**Comment by ahmadawais** [comment]
Glad you liked it.
