### ISSUE TITLE
Always stuck on installation

### ISSUE THREAD

**Issue by dameer** [ahmadawais/create-guten-block#74]
MacOS Sierra 10.12.6

At first I had to change read/write permission on 'node_modules' because of permission denied error.
After changing permission to that folder installation runs fine until

` extract:is-ci: sill extract npm-run-path@2.0.2`

...and this is where things hang forever. Can't move on. No error or whatsoever.
Any ideas?

**Comment by ahmadawais** [comment]
Thanks for creating the issue, but follow the bug report format if you'd like us to help you, it has info we need to process the bug report.

**Comment by dameer** [comment]
Just figured it out.
For all of people having permission issues with installation, use "sudo" prefix to grant required permissions on MacOS. So, in case you are EACCESS stuck do:

`sudo npm install create-guten-block --global`

...rather than just 

`npm install create-guten-block --global`

That's all.

Ahmad, thanks for all your efforts with regards to this tool and thanks for a speedy response! God bless!

**Comment by ahmadawais** [comment]
^ @dameer  you don't seem to be following the documentation. I recommend against installing create-guten-block as a global module. Read the docs https://github.com/ahmadawais/create-guten-block#%EF%B8%8F-quick-overview

**Comment by dameer** [comment]
That's what's been recommended by your own/official website : https://ahmadawais.com/create-guten-block-toolkit/#user-content--step-1 

Am I missing the point?

**Comment by ahmadawais** [comment]
@dameer the post is old, GitHub repo's readme is up to date. I am glad you pointed that out so now I know the source of misinformation being spread for a couple of months 👍

**Comment by ahmadawais** [comment]
I just updated the blogpost 👍
