### ISSUE TITLE
@wordpress imports fail

### ISSUE THREAD

**Issue by strarsis** [ahmadawais/create-guten-block#80]
### Expected Behavior

WordPress dependencies should be `@import`ed correctly.

### Actual Behavior

Import error:
```
Module not found: Can't resolve '@wordpress/blocks' in '[...]/slider-block/src/slider'
````

### Steps to Reproduce

1. Add some imports for Gutenberg core modules:
```js
/**
 * WordPress dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { PanelBody, RangeControl } from '@wordpress/components';
import { Fragment } from '@wordpress/element';
import { createBlock } from '@wordpress/blocks';
import {
	InspectorControls,
	InnerBlocks,
} from '@wordpress/editor';
````
2. Build (or watch) and notice in terminal the import error:
```
Module not found: Can't resolve '@wordpress/blocks' in '[...]/slider-block/src/slider'
````

1. `node -v`: v8.11.4
2. `npm -v`: 5.6.0
3. `yarn --version` (if you use Yarn): 1.9.4
4. `npm ls cgb-scripts` (if you haven’t ejected):
````
slider-block-cgb-guten-block@1.0.0 [...]/slider-block
                     └── UNMET DEPENDENCY cgb-scripts@1.9.7
````
I ensured it is installed by using `yarn add --dev cgb-scripts@1.9.7`.
I used `npm` for installing the dependencies instead of `yarn` and the error message went away, 
`npm ls` seems to have compatibility issues with yarn dependency installations.
This doesn't seem to be related to the reported issue.

Then, specify:

1. Operating system: Windows 10 Pro x64, WSL (Bash on Windows)
2. Browser and version (if relevant): (Not relevant / applicable, node/terminal)

### Reproducible Demo

Create empty boilerplate app and add these imports to `./src/<block-name>/block.js`:
```js
/**
 * WordPress dependencies
 */
import { __, sprintf } from '@wordpress/i18n';
import { PanelBody, RangeControl } from '@wordpress/components';
import { Fragment } from '@wordpress/element';
import { createBlock } from '@wordpress/blocks';
import {
	InspectorControls,
	InnerBlocks,
} from '@wordpress/editor';
````

**Comment by SunnyJohal** [comment]
@strarsis are you installing the packages in your project? (are they in your package.json file as dependancies) Also all of the packages that you have listed are available on the global window object when WordPress loads the editor. E.g. For your boilerplate:

```js
const { wp } = window;
import { __, sprintf } from wp.i18n;
import { PanelBody, RangeControl } from  wp.components;
import { Fragment } from wp.element;
import { createBlock } from wp.blocks;
import {
	InspectorControls,
	InnerBlocks,
} from wp.editor;
```

**Comment by strarsis** [comment]
@SunnyJohal: So the boilerplate should declare these as global so that webpack doesn't try to load them as node modules? Otherwise this boilerplate is missing these WordPress core packages as dependencies.

**Comment by SunnyJohal** [comment]
Hi @strarsis,
I'm not sure that I understand your issue? If you are pulling them off the global window object then webpack won't try to load them as node modules. What is it that you are looking to do?

**Comment by SunnyJohal** [comment]
@strarsis I updated that code example as I made a typo.

**Comment by ahmadawais** [comment]
Happy to accept a PR if anyone interested. I can get to it later next week.

**Comment by strarsis** [comment]
@SunnyJohal: I am re-using the code from [Gutenberg Columns block](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/columns/column.js).
Hence I thought this should just work out of the box as these imports seem to be required for a block.

**Comment by strarsis** [comment]
@ahmadawais: Would it make sense to add/reuse the babel and webpack config that the Gutenberg repo uses?
- https://github.com/WordPress/gutenberg/blob/master/babel.config.js
- https://github.com/WordPress/gutenberg/blob/master/webpack.config.js

**Comment by strarsis** [comment]
So in WordPress Gutenberg project itself (built-in blocks), 
the WordPress Gutenberg packages are resolved internally to 
`packages/` directory (they use lerna for dependency management).
The packages are also published to npm, e.g. [`@wordpress/blocks`](https://www.npmjs.com/package/@wordpress/blocks/v/1.0.0).

I added these packages explictily and build works now.

**Comment by strarsis** [comment]
```js
/**
 * WordPress dependencies
 */
const { __, sprintf }       = wp.i18n;
const { registerBlockType } = wp.blocks;
const { PanelBody, RangeControl } = wp.components;
const { Fragment } = wp.element;
const {
	InspectorControls,
	InnerBlocks,
} = wp.editor;
````
