### ISSUE TITLE
How to run on the existing folder

### ISSUE THREAD

**Issue by llemurya** [ahmadawais/create-guten-block#81]
Hello, I have an existing plugin and I want to create the gutenberg block in its directory, but in the console is shown an warning suggestion message:

> A directory with this name already exists, Please move or delete it (maybe make a copy for backup) and run this command again. Or provide a different name for your block.

How can do this kind of stuff? 
Thanks.

**Comment by SunnyJohal** [comment]
You can install `cgb-scripts` as a dependancy in your package.json file by running:
`npm install --save cgb-scripts`

Then add the appropriate script commands to your package.json file:
```json
  "scripts": {
    "start": "cgb-scripts start",
    "build": "cgb-scripts build",
    "eject": "cgb-scripts eject"
  }
```
Then just run `npm start` and it should work

**Comment by SunnyJohal** [comment]
Also, if you do this then in your plugin directory you need to make sure that you enqueue the scripts into the editor. E.g.:
```php
/**
 * Load Block Assets
 *
 * Enqueue Gutenberg block assets for both frontend
 * and backend.
 *
 * @todo Organise the assets and frontend js.
 * @return void
 */
function my_plugin_blocks_load_assets() {
	wp_enqueue_style(
		'my-plugin-blocks',
		plugins_url( 'dist/blocks.style.build.css', dirname( __FILE__ ) ),
		array( 'wp-blocks' )
	);
}
add_action( 'enqueue_block_assets', 'my_plugin_blocks_load_assets' );

/**
 * Enqueue Gutenberg block assets for backend editor.
 *
 * `wp-blocks`: includes block type registration and related functions.
 * `wp-element`: includes the WordPress Element abstraction for describing the structure of your blocks.
 * `wp-i18n`: To internationalize the block's text.
 *
 * @return void
 */
function my_plugin_blocks_editor_assets() {
	wp_enqueue_script(
		'my-plugin-block-editor',
		plugins_url( '/dist/blocks.build.js', dirname( __FILE__ ) ),
		array( 'wp-blocks', 'wp-i18n', 'wp-element' ),
		true
	);

	wp_enqueue_style(
		'my-plugin-block-editor',
		plugins_url( '/dist/blocks.editor.build.css', dirname( __FILE__ ) ),
		array( 'wp-edit-blocks' )
	);
}
add_action( 'enqueue_block_editor_assets', 'my_plugin_blocks_editor_assets' );
```

and you need to create a new directory in your plugin directory called `src` and create two new files in that directory: `common.scss` and `blocks.js`
