### ISSUE TITLE
Include all components of wp.editor/wp.element/wp.component/wp.blocks in the block.js file

### ISSUE THREAD

**Issue by AshiqKiron** [ahmadawais/create-guten-block#87]
This is my current imported components from WP core 

```
// let's us call registerBlockType() directly from the wp.blocks library
const { registerBlockType, getPhrasingContentSchema, children  } = wp.blocks;
 
 
// let's us use the withAPIData() function from the wp.components library to access the Rest API
const {
    withAPIData,
    PanelBody,
	PanelRow,
	Button,
	IconButton,
	URLInput,
	Dashicon,
	Toolbar,
	SelectControl,
	RangeControl,
	PanelColorSettings,
    ToggleControl,
	withFallbackStyles,
    FormToggle } = wp.components;
 
// let's us use the __() function from the wp.i18n library to translate strings
const { __ } = wp.i18n;
  

const { RawHTML, Fragment, Component } = wp.element;
const {
    RichText,
    BlockControls,
    InspectorControls,
	AlignmentToolbar,
	MediaUpload,
	ColorPalette, 
    PanelColor,
    getColorClassName,
    getFontSizeCass,
	withColors,
    ContrastChecker,
    FontSizePicker,
	withFontSizes,
} = wp.editor;
```

I'm sure there are plenty more to add, The problem is it really is a hassle to search and include the components in the right WP category. Not to mention, sometimes blocks wouldn't work if you've imported in the wrong way.

Why not include them all ? 

Potential problem? 
Everything will be loaded.Well, You can comment out majority of them, developer will have to just **uncomment** to use that component.

**Comment by ahmadawais** [comment]
Not sure how this has anything to do with create-guten-block. That's a development question. You can develop any way you like. Not going to endorse including stuff you don't need. Actually, my personal workflow of ESLint kicks the stuff out of the file which was never used.
