### ISSUE TITLE
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In [...]/babel-preset-cgb/index.js

### ISSUE THREAD

**Issue by braco** [ahmadawais/create-guten-block#88]
## Bug Report

Trying to include create-guten-block in a larger project via [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/).  I'm assuming this is a problem with conflicting babel versions, but this "shouldn't happen".

The directory layout is like this:
```
project/
    create-guten-block/
    other-package1/
    other-package2/
```

`start` yields this:
```
❌   Failed to compile.

👉  ./src/blocks.js
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In /[...]/node_modules/babel-preset-cgb/index.js
    at Array.map (<anonymous>)
```

I'll update this issue if I can track this bug down.

**Comment by ahmadawais** [comment]
This is not a bug, this looks like a feature request. We don't have support for large complex workspaces based projects. That's where you do custom stuff. Maybe hire me to configure that project coz otherwise adding features for many just to support one project might not be the right idea. 🙌

**Comment by braco** [comment]
For anyone else who finds this, it's fixed by upgrading the outdated babel packages

https://github.com/babel/babel-loader/issues/540

**Comment by ahmadawais** [comment]
So you must be using Babel 7 since the changed everything then and moved to namespaced packages.

**Comment by braco** [comment]
I'm not using babel at all on the top level, so I guess it has something to do with resolution and conflicting versions somewhere in one of the workspaces / child packages. Not sure yet why there isn't more isolation.

**Comment by jameskhamil** [comment]
I am getting this problem too.

This package is using outdated methods, with things like babel-core instead of @babel/core. It needs to be updated.

**Comment by jameskhamil** [comment]
@braco I could not update like that because it's a problem with the babel configs used in this project. How did you fix?

**Comment by ahmadawais** [comment]
@jameskhamil The package is working fine. You must be using the latest Babel/webpack which are not yet supported by this project. Calling a working project outdated may not be the best course of action. Downvoting and laughing don't get anyone anywhere. What you can do instead is spend time on the project and update it. I can't handle the support load of it all by myself, being a self-employed open source dev.

PR for this is most welcomed, in a complete fashion where Babel 7 support is added and webpack 4 support is added as well.
