### ISSUE TITLE
Win32: Test Run Successful 🎉

### ISSUE THREAD

**Issue by MrSaqibAmeen** [ahmadawais/create-guten-block#9]
### Is this a bug report?
No

### Environment
1. `node -v`: 9.2.0
2. `npm -v`: 5.5.1
3. `yarn --version` (if you use Yarn): NA
4. `npm ls cgb-scripts` (if you haven’t ejected): NA

Then, specify:

1. Operating system: Windows 8.1 x64
2. Browser and version (if relevant): Chrome v62.0.3202.94

### Steps to Reproduce
I tested the latest version on windows 8.1, following are my tests and results:

- [x] `npm install create-guten-block --global` 
- [x] `create-guten-block b3` – gives an error `Directory already exists` but works perfectly fine. 
![image](https://user-images.githubusercontent.com/31374163/35163019-1ef0cf0a-fd67-11e7-860c-c252442cf9d4.png)
```
A subdirectory or file -p already exists.
Error occurred while processing: -p.
```
- [x] `npm run start` – compiles successfully, and watches for the changes.
I tried removing `<` in `<p>` tags, gave error: 
![image](https://user-images.githubusercontent.com/31374163/35163285-03ecb178-fd68-11e7-96bb-46d2aab46580.png)
- [x] `npm run build` – successfully produce production builds
- [x] `CSS and Block Content Changes` – Changed colors & block content from `b3` to `by Saqib` successfully works on local installation.

![image](https://user-images.githubusercontent.com/31374163/35163813-c8898546-fd69-11e7-8615-c8db6b8aff33.png)

and a GIF:
![screen recording 2018-01-19 at 10 35 30 pm](https://user-images.githubusercontent.com/31374163/35163626-35e3bd1a-fd69-11e7-95cd-869fd9880e3c.gif)
- [x] `npm run eject` – works successfully. Then I run  `npm run start` and it repeated same tests - works fine. 
- [x] `npm run build` – success!

All fine from my end. So 👍

**Comment by ahmadawais** [comment]
@MrSaqibAmeen Thanks a lot for testing it on Windows. 👏

**Comment by MrSaqibAmeen** [comment]
It was great to test and help. Got to learn something. 💯

**Comment by ahmadawais** [comment]
BTW Welcome to the project as a Windows user + Collaborator.
