### ISSUE TITLE
Need article or example to add new control such as icon picker for gutenberg?

### ISSUE THREAD

**Issue by prajaktagadhave** [ahmadawais/create-guten-block#91]
Hello,

I want article or examples about how to add new custom control for the Gutenberg. I didn't get any relevant link regarding this.

Can you please help me?

I want to create a control like this to select icon - https://goo.gl/SYwBA5

How can I achieve this?

Any suggestion and guidance will be highly appreciable.

Thanks.

**Comment by ahmadawais** [comment]
Closed for not being an issue. Feel free to ask people to join in the discussions here.
