### ISSUE TITLE
create-guten-block not working for me

### ISSUE THREAD

**Issue by oussamaBGZ** [ahmadawais/create-guten-block#99]
## Bug Report

this is the err in my console:

```bash
npx create-guten-block my-block

📦   Creating a WP Gutenberg Block plugin called:  my-block

 In the directory: G:\ApacheServer\htdocs\wordpress\wp-content\plugins\my-block
 This might take a couple of minutes.

√ 1. Creating the plugin directory called →  my-block
\ 2. Installing npm packages...C:\Users\oussa\AppData\Roaming\npm\node_modules\create-guten-block\index.js:60
        throw err;
        ^

Error: Command failed: npm install cgb-scripts --save --save-exact --slient
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! Unexpected end of JSON input while parsing near '...c735ca15e4e7513b3","t'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oussa\AppData\Roaming\npm-cache\_logs\2018-10-20T17_29_56_864Z-debug.log
```

=> `node -v`: v10.12.0
=> `npm -v`: 6.3.0
=> Operating system: windows 10  64-bit
=> Browser and version (if relevant): Version 69.0.3497.100 (Build officiel) (64 bits)

**Comment by ahmadawais** [comment]
Something is wrong with Windows. Can you send me the complete log for the this particular command that you ran placed at `C:\Users\oussa\AppData\Roaming\npm-cache\_logs\2018-10-20T17_29_56_864Z-debug.log`

**Comment by oussamaBGZ** [comment]
> Something is wrong with Windows. Can you send me the complete log for the this particular command that you ran placed at `C:\Users\oussa\AppData\Roaming\npm-cache\_logs\2018-10-20T17_29_56_864Z-debug.log`

i just updated npm to 6.4.1 and clean the cache folder and it's worked
